server:
  port: 8096
spring:
  application:
    name: sso-center
  devtools:
    restart:
      enabled: true
      additional-paths: /src/main/java
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/

