server:
  port: 8090

spring:
  application:
    name: tomorrow_server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8090/eureka/