server:
  port: 8094

spring:
  application:
    name: user_center
  devtools:
    restart:
      additional-paths: /src/main/java
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka