server:
  port: 8092
spring:
  application:
    name: zuul_server
  devtools:
    restart:
      additional-paths: /src/main/java
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka
zuul:
  routes:
    baidu:
      path: /api/**
      url: http://www.baidu.com
